### ISSUE TITLE
Regarding issues I am facing while running PPO.py 

### ISSUE THREAD

**Issue by AshuKV** [marooncn/navbot#1]
I have installed all the dependencies required for running PPO.py file successfully. The problem is that for running code python2.7 is required so I had installed python2.7 for the same. All the dependencies installed successfully except Tensorforce and the issue I am facing while installing tensorforce that now tensorforce doesn't support on python2.7.

So it will be helpful for me if you can guide me to solve this issue. Thanks in advance.

**Comment by marooncn** [comment]
You can use the old version of tensorforce that supports python 2.7.
