### ISSUE TITLE
Robot only spin but not move

### ISSUE THREAD

**Issue by MineIdea** [marooncn/navbot#3]
Dear maroocn,
    I run PPO.py successfully,but I find the robot in gazebo gui does not move toward the goal,it only spin at the start position.Is it normal?

**Comment by marooncn** [comment]
Sorry for the late reply, maybe you can try the different action space to make the robot choose high linear speed and low angular speed more easily.

**Comment by MineIdea** [comment]
I download the turtlebot online which is not  same of yours and this caused many problems.I will try to solve it.Thank you for your reply!
