### ISSUE TITLE
something wrong about tensorflow

### ISSUE THREAD

**Issue by GongYanfu** [marooncn/navbot#7]
I want to know how do you install tensorflow? when I install it, there is something wrong.
![image](https://user-images.githubusercontent.com/46698455/178088001-b1999b5d-b2d5-46ff-8d0c-c1b4f16d1096.png)

**Comment by GongYanfu** [comment]
I found solution,sorry

**Comment by zhang-mu-zhi** [comment]
How did you solve this problem?

**Comment by GongYanfu** [comment]
try to install protobuf first

**Comment by GongYanfu** [comment]
I cantrun this project successfully

**Comment by zhang-mu-zhi** [comment]
How did you run the project successfully
I mean: what version of Ubuntu are you using? What version of ROS are you using? What version of Python are you using? and other environmental requirements.

**Comment by zhang-mu-zhi** [comment]
I would like to ask you some other questions. How should I contact you? My e-mail: qq418062417@gmail.com. Very much looking forward to your reply.

**Comment by GongYanfu** [comment]
No sorry.
I cannt run this repo successfully
I gave up before

**Comment by zhang-mu-zhi** [comment]
Well, I can't run this code either.
Have you seen other similar codes? Can you recommend it to me?
Thank you very much.

**Comment by zhang-mu-zhi** [comment]
What I mean is that in the process of robot navigation, the robot input is the current state of the robot, the RGB image obtained by the robot camera, and the coordinates of the target point.
These inputs are processed by the CNN network to obtain the robot's action instructions, such as moving forward or turning.

The robot in this code navigates in this way.

Have you seen other similar codes? Can you recommend it to me?
Thank you very much.

**Comment by GongYanfu** [comment]
I think you shoud search some papers about DRL or RL for robot visual navigation

**Comment by zhang-mu-zhi** [comment]
Thank you very much for your suggestion, I will read the paper you recommend.
